# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'journal_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JournalWindow(object):
    def setupUi(self, JournalWindow):
        JournalWindow.setObjectName("JournalWindow")
        JournalWindow.resize(1919, 867)
        JournalWindow.setStyleSheet("QWidget[objectName=\"centralwidget\"] { background-color: #f6f8fa; }\n"
                                    "QTableWidget[objectName=\"table\"] { border: 1px solid black; }")
        self.centralwidget = QtWidgets.QWidget(JournalWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 15, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.journal_info = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.journal_info.setFont(font)
        self.journal_info.setAlignment(QtCore.Qt.AlignCenter)
        self.journal_info.setObjectName("journal_info")
        self.horizontalLayout.addWidget(self.journal_info)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.journal_teacher = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.journal_teacher.setFont(font)
        self.journal_teacher.setText("")
        self.journal_teacher.setAlignment(QtCore.Qt.AlignCenter)
        self.journal_teacher.setObjectName("journal_teacher")
        self.horizontalLayout_2.addWidget(self.journal_teacher)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.table = QtWidgets.QTableView(self.frame)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setObjectName("table")
        self.horizontalLayout_3.addWidget(self.table)
        spacerItem1 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        JournalWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(JournalWindow)
        QtCore.QMetaObject.connectSlotsByName(JournalWindow)

    def retranslateUi(self, JournalWindow):
        _translate = QtCore.QCoreApplication.translate
        JournalWindow.setWindowTitle(_translate("JournalWindow", "MainWindow"))
        self.journal_info.setText(
            _translate("JournalWindow", "Группа: П2-19; Дисциплина: Иностарнный язык; Семестр: 6"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    JournalWindow = QtWidgets.QMainWindow()
    ui = Ui_JournalWindow()
    ui.setupUi(JournalWindow)
    JournalWindow.show()
    sys.exit(app.exec_())
