# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Authorization(object):
    def setupUi(self, Authorization):
        Authorization.setObjectName("Authorization")
        Authorization.resize(562, 397)
        Authorization.setMinimumSize(QtCore.QSize(562, 397))
        Authorization.setMaximumSize(QtCore.QSize(562, 400))
        Authorization.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Authorization.setAutoFillBackground(False)
        Authorization.setStyleSheet("QWidget[objectName=\"Authorization\"] { background-color: #f6f7fb }")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Authorization)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_8 = QtWidgets.QFrame(Authorization)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon = QtWidgets.QLabel(self.frame_7)
        self.icon.setStyleSheet("    min-height: 131px;\n"
"    max-height: 131px;\n"
"    min-width: 181px;\n"
"    max-width: 181px;")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("../icons/logo.svg"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_10.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.text = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.text.setFont(font)
        self.text.setAlignment(QtCore.Qt.AlignCenter)
        self.text.setObjectName("text")
        self.verticalLayout_8.addWidget(self.text)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addWidget(self.frame_6)
        self.frame = QtWidgets.QFrame(self.frame_5)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.login = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Montserrat 6")
        font.setPointSize(-1)
        self.login.setFont(font)
        self.login.setStyleSheet("QLineEdit {\n"
"    min-height: 41px;\n"
"    max-height: 41px;\n"
"    border: 1px solid #e7e7e7;\n"
"    backgorund-color: #fbfbfb;\n"
"    border-radius: 20px;\n"
"    font-family: Montserrat Medium;\n"
"    font-size: 15px;\n"
"    padding-left: 1em;\n"
"}")
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setStyleSheet("QLineEdit {\n"
"    min-height: 41px;\n"
"    max-height: 41px;\n"
"    border: 1px solid #e7e7e7;\n"
"    backgorund-color: #fbfbfb;\n"
"    border-radius: 20px;\n"
"    font-family: Montserrat Medium;\n"
"    font-size: 15px;\n"
"    padding-left: 1em;\n"
"    padding-right: 1em;\n"
"}")
        self.password.setText("")
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_10.addWidget(self.frame)
        self.verticalLayout_11.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.frame_8)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 40, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.remember = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift 53")
        font.setPointSize(-1)
        self.remember.setFont(font)
        self.remember.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remember.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.remember.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.remember.setAutoFillBackground(False)
        self.remember.setStyleSheet("QPushButton {\n"
"    color: black;\n"
"    font-size: 14px;\n"
"    font-family: Bahnschrift Light;\n"
"    background-color: transparent; \n"
"    border: 1px solid transparent;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    color: blue;\n"
"    background-color:transparent ;\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    color: blue;\n"
"    background-color: transparent;\n"
"    border-color: transparent;\n"
"}")
        self.remember.setObjectName("remember")
        self.horizontalLayout_2.addWidget(self.remember)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout_3.setSpacing(9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.entry = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(-1)
        self.entry.setFont(font)
        self.entry.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.entry.setStyleSheet("QPushButton {\n"
"    max-weight: 50px;\n"
"    min-weight: 50px;\n"
"    max-height: 25px;\n"
"    min-height: 25px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    font-family: Bahnschrift SemiBold;\n"
"    background-color: #3f5cde; \n"
"    border: 1px solid #3f5cde;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    color: white;\n"
"    background-color: #243581;\n"
"    border-color: #243581;\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    color: white;\n"
"    background-color: #243581;\n"
"    border-color: #243581;\n"
"}")
        self.entry.setObjectName("entry")
        self.verticalLayout_3.addWidget(self.entry)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_11.addWidget(self.frame_3)
        self.verticalLayout_6.addWidget(self.frame_8)

        self.retranslateUi(Authorization)
        QtCore.QMetaObject.connectSlotsByName(Authorization)

    def retranslateUi(self, Authorization):
        _translate = QtCore.QCoreApplication.translate
        Authorization.setWindowTitle(_translate("Authorization", "Окно авторизации"))
        self.text.setText(_translate("Authorization", "Авторизация"))
        self.login.setPlaceholderText(_translate("Authorization", "Логин"))
        self.password.setPlaceholderText(_translate("Authorization", "Пароль"))
        self.remember.setText(_translate("Authorization", "Не могу войти"))
        self.entry.setText(_translate("Authorization", "ВОЙТИ"))
        self.entry.setShortcut(_translate("Authorization", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Authorization = QtWidgets.QWidget()
    ui = Ui_Authorization()
    ui.setupUi(Authorization)
    Authorization.show()
    sys.exit(app.exec_())
